{"name": "Запрос с несуществующим номером заказа возвращает ошибку", "status": "passed", "start": 1734236891270, "stop": 1734236898270, "uuid": "ababb400-9d0c-4b66-a923-731ae5034135", "historyId": "4c341fdd627022bf3ba57c5751466372", "testCaseId": "4c341fdd627022bf3ba57c5751466372", "fullName": "test_get_order_by_track_nonexistent_number.TestGetOrderByTrackNonexistentNumber#test_get_order_by_track_nonexistent_number", "labels": [{"name": "feature", "value": "Получение заказа по несуществующему номеру"}, {"name": "suite", "value": "test_get_order_by_track_nonexistent_number"}, {"name": "subSuite", "value": "TestGetOrderByTrackNonexistentNumber"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "1612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_get_order_by_track_nonexistent_number"}]}