{"name": "Запрос с несуществующим номером заказа возвращает ошибку", "status": "passed", "start": 1734602265927, "stop": 1734602266752, "uuid": "e9faa20d-32ba-4ddf-a8ff-7a5c6bd446dc", "historyId": "c2cf292c498bdf6db453e62c6998f5e0", "testCaseId": "c2cf292c498bdf6db453e62c6998f5e0", "fullName": "tests.orders.get_order.test_get_order_by_track_nonexistent_number.TestGetOrderByTrackNonexistentNumber#test_get_order_by_track_nonexistent_number", "labels": [{"name": "feature", "value": "Получение заказа по несуществующему номеру"}, {"name": "parentSuite", "value": "tests.orders.get_order"}, {"name": "suite", "value": "test_get_order_by_track_nonexistent_number"}, {"name": "subSuite", "value": "TestGetOrderByTrackNonexistentNumber"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "5388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.get_order.test_get_order_by_track_nonexistent_number"}]}