{"name": "Попытка принять заказ с некорректным ID заказа", "status": "passed", "steps": [{"name": "Принятие заказа курьером", "status": "passed", "parameters": [{"name": "order_id", "value": "3633333"}, {"name": "courier_id", "value": "442129"}], "start": 1735025485133, "stop": 1735025485946}], "attachments": [{"name": "stdout", "source": "db1e7ed7-ca41-49e1-8974-a597beb2ddae-attachment.txt", "type": "text/plain"}], "start": 1735025485133, "stop": 1735025485947, "uuid": "9833e872-f8f4-4de4-9b23-2ad767868197", "historyId": "281945cd09d5afbb0ae43a4b6d79f5d7", "testCaseId": "281945cd09d5afbb0ae43a4b6d79f5d7", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_invalid_order_id", "labels": [{"name": "feature", "value": "Принятие заказа"}, {"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "2456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}